import { AppSettings } from './types';

export const DEFAULT_SETTINGS: AppSettings = {
  darkMode: false,
  learningSteps: [1, 10],
  newCardsPerDay: 999,
  reviewsPerDay: 999,
  initialEaseFactor: 2.5,
  easyBonus: 1.3,
};

export const DB_NAME = 'AnkiDrugDB';
export const DB_VERSION = 4; // Bumped for classification field

export const HAMILTON_DECK_ID = 'deck_hamilton_v1';
export const CARDIO_DECK_ID = 'deck_cardio_v1';

export const MIN_EASE_FACTOR = 1.3;

export const INTERVALS = {
  AGAIN: 1 * 60 * 1000,
  HARD: 3 * 60 * 1000,
  GOOD: 15 * 60 * 1000,
  EASY: 60 * 60 * 1000,
};

export const COLORS = {
  again: 'bg-red-500 hover:bg-red-600 dark:bg-red-600 dark:hover:bg-red-700',
  hard: 'bg-orange-500 hover:bg-orange-600 dark:bg-orange-600 dark:hover:bg-orange-700',
  good: 'bg-green-500 hover:bg-green-600 dark:bg-green-600 dark:hover:bg-green-700',
  easy: 'bg-blue-500 hover:bg-blue-600 dark:bg-blue-600 dark:hover:bg-blue-700',
};

export const HAMILTON_DATA = [
  { generic: "acetaminophen", brand: "Tylenol", classification: "Analgesic/Antipyretic" },
  { generic: "acetylsalicylic acid", brand: "Aspirin", classification: "NSAID/Antiplatelet" },
  { generic: "acyclovir", brand: "Zovirax", classification: "Antiviral" },
  { generic: "adenosine", brand: "Adenocard", classification: "Antiarrhythmic" },
  { generic: "amiodarone", brand: "Cordarone", classification: "Antiarrhythmic (Class III)" },
  { generic: "amlodipine", brand: "Norvasc", classification: "Calcium Channel Blocker (DHP)" },
  { generic: "amoxicillin/potassium clavulanate", brand: "Clavulin", classification: "Antibiotic (Penicillin)" },
  { generic: "apixaban", brand: "Eliquis", classification: "Anticoagulant (DOAC)" },
  { generic: "atorvastatin", brand: "Lipitor", classification: "Statins (HMG-CoA Reductase Inhibitor)" },
  { generic: "atropine sulfate", brand: "Isopto Atropine", classification: "Anticholinergic" },
  { generic: "azithromycin", brand: "Zithromax", classification: "Antibiotic (Macrolide)" },
  { generic: "bacitracin/polymyxin", brand: "Polysporin", classification: "Topical Antibiotic" },
  { generic: "bisacodyl", brand: "Dulcolax", classification: "Stimulant Laxative" },
  { generic: "bisoprolol", brand: "Monocor", classification: "Beta-Blocker (Cardioselective)" },
  { generic: "bupivacaine", brand: "Marcaine", classification: "Local Anesthetic" },
  { generic: "calcium carbonate", brand: "Tums", classification: "Antacid/Calcium Supplement" },
  { generic: "calcium chloride", brand: "Calciject", classification: "Electrolyte" },
  { generic: "calcium citrate", brand: "Caltrate", classification: "Calcium Supplement" },
  { generic: "candesartan", brand: "Atacand", classification: "ARB (Hypertension)" },
  { generic: "carbetocin", brand: "Duratocin", classification: "Oxytocic" },
  { generic: "cefazolin", brand: "Ancef", classification: "Antibiotic (Cephalosporin 1st Gen)" },
  { generic: "ceftazidime", brand: "Fortaz", classification: "Antibiotic (Cephalosporin 3rd Gen)" },
  { generic: "ceftriaxone", brand: "Rocephin", classification: "Antibiotic (Cephalosporin 3rd Gen)" },
  { generic: "cefuroxime", brand: "Zinacef", classification: "Antibiotic (Cephalosporin 2nd Gen)" },
  { generic: "cephalexin", brand: "Keflex", classification: "Antibiotic (Cephalosporin 1st Gen)" },
  { generic: "cetirizine", brand: "Reactine", classification: "Antihistamine (2nd Gen)" },
  { generic: "cholecalciferol", brand: "Vitamin D3", classification: "Vitamin" },
  { generic: "ciprofloxacin", brand: "Cipro", classification: "Antibiotic (Fluoroquinolone)" },
  { generic: "clopidogrel", brand: "Plavix", classification: "Antiplatelet" },
  { generic: "cyanocobalamin", brand: "Vitamin B-12", classification: "Vitamin" },
  { generic: "dalteparin", brand: "Fragmin", classification: "Anticoagulant (LMWH)" },
  { generic: "dexamethasone", brand: "Decadron", classification: "Corticosteroid" },
  { generic: "digoxin", brand: "Toloxin", classification: "Cardiac Glycoside" },
  { generic: "diltiazem", brand: "Cardizem", classification: "Calcium Channel Blocker (Non-DHP)" },
  { generic: "dimenhydrinate", brand: "Gravol", classification: "Antiemetic/Antihistamine" },
  { generic: "diphenhydramine", brand: "Benadryl", classification: "Antihistamine (1st Gen)" },
  { generic: "enoxaparin", brand: "Lovenox", classification: "Anticoagulant (LMWH)" },
  { generic: "epinephrine", brand: "Adrenalin", classification: "Adrenergic Agonist" },
  { generic: "ertapenem", brand: "Invanz", classification: "Antibiotic (Carbapenem)" },
  { generic: "fentanyl", brand: "Sublimaze", classification: "Opioid Analgesic" },
  { generic: "fondaparinux", brand: "Arixtra", classification: "Anticoagulant (Factor Xa Inhibitor)" },
  { generic: "furosemide", brand: "Lasix", classification: "Loop Diuretic" },
  { generic: "gabapentin", brand: "Neurontin", classification: "Anticonvulsant/Neuropathic Agent" },
  { generic: "haloperidol", brand: "Haldol", classification: "Antipsychotic (Typical)" },
  { generic: "hydralazine", brand: "Apresoline", classification: "Vasodilator" },
  { generic: "hydrocortisone sodium succinate", brand: "Cortef", classification: "Corticosteroid" },
  { generic: "hydromorphone", brand: "Dilaudid", classification: "Opioid Analgesic" },
  { generic: "ibuprofen", brand: "Advil", classification: "NSAID" },
  { generic: "insulin glargine", brand: "Lantus", classification: "Insulin (Long-Acting)" },
  { generic: "insulin lispro", brand: "Humalog", classification: "Insulin (Rapid-Acting)" },
  { generic: "insulin regular", brand: "Humulin R", classification: "Insulin (Short-Acting)" },
  { generic: "ipratropium", brand: "Atrovent", classification: "Anticholinergic (Bronchodilator)" },
  { generic: "iron sucrose", brand: "Venofer", classification: "Iron Supplement" },
  { generic: "ketamine", brand: "Ketalar", classification: "General Anesthetic/Dissociative" },
  { generic: "ketorolac", brand: "Toradol", classification: "NSAID (Injectable)" },
  { generic: "labetalol", brand: "Trandate", classification: "Alpha/Beta-Blocker" },
  { generic: "levetiracetam", brand: "Keppra", classification: "Anticonvulsant" },
  { generic: "levothyroxine sodium", brand: "Synthroid", classification: "Thyroid Hormone" },
  { generic: "lidocaine", brand: "Xylocaine", classification: "Local Anesthetic/Antiarrhythmic" },
  { generic: "lorazepam", brand: "Ativan", classification: "Benzodiazepine" },
  { generic: "metformin", brand: "Glucophage", classification: "Antidiabetic (Biguanide)" },
  { generic: "metoclopramide", brand: "Maxeran", classification: "Antiemetic/Prokinetic" },
  { generic: "metoprolol", brand: "Lopressor", classification: "Beta-Blocker (Cardioselective)" },
  { generic: "metronidazole", brand: "Flagyl", classification: "Antibiotic (Nitroimidazole)" },
  { generic: "midazolam", brand: "Versed", classification: "Benzodiazepine (Sedative)" },
  { generic: "morphine", brand: "Statex", classification: "Opioid Analgesic" },
  { generic: "naloxone", brand: "Narcan", classification: "Opioid Antagonist" },
  { generic: "naproxen", brand: "Aleve", classification: "NSAID" },
  { generic: "neostigmine methylsulfate", brand: "Prostigmin", classification: "Acetylcholinesterase Inhibitor" },
  { generic: "nitroglycerin", brand: "Nitrostat", classification: "Nitrate (Vasodilator)" },
  { generic: "norepinephrine", brand: "Levophed", classification: "Vasopressor" },
  { generic: "ondansetron", brand: "Zofran", classification: "Antiemetic (5-HT3 Antagonist)" },
  { generic: "oxytocin", brand: "Pitocin", classification: "Oxytocic Hormone" },
  { generic: "pantoprazole", brand: "Pantoloc", classification: "Proton Pump Inhibitor (PPI)" },
  { generic: "phenylephrine HCl", brand: "Mydfrin", classification: "Alpha-1 Agonist" },
  { generic: "phytonadione", brand: "Vitamin K", classification: "Vitamin/Coagulant" },
  { generic: "piperacillin sodium/tazobactam", brand: "Tazocin", classification: "Antibiotic (Extended Spectrum)" },
  { generic: "polyethylene glycol 3350", brand: "Restoralax", classification: "Osmotic Laxative" },
  { generic: "prednisone", brand: "Deltasone", classification: "Corticosteroid" },
  { generic: "pregabalin", brand: "Lyrica", classification: "Anticonvulsant/Neuropathic Agent" },
  { generic: "propofol", brand: "Diprivan", classification: "General Anesthetic (IV)" },
  { generic: "quetiapine fumarate", brand: "Seroquel", classification: "Antipsychotic (Atypical)" },
  { generic: "ramipril", brand: "Altace", classification: "ACE Inhibitor" },
  { generic: "remifentanil", brand: "Ultiva", classification: "Opioid Analgesic" },
  { generic: "rivaroxaban", brand: "Xarelto", classification: "Anticoagulant (Factor Xa Inhibitor)" },
  { generic: "rocuronium", brand: "Zemuron", classification: "Neuromuscular Blocker" },
  { generic: "rosuvastatin", brand: "Crestor", classification: "Statins" },
  { generic: "salbutamol", brand: "Ventolin", classification: "Beta-2 Agonist (Bronchodilator)" },
  { generic: "sennosides", brand: "Senokot", classification: "Stimulant Laxative" },
  { generic: "sodium chloride 3 %", brand: "Hypertonic Saline", classification: "Electrolyte Solution" },
  { generic: "sodium phosphates", brand: "Fleet", classification: "Laxative" },
  { generic: "sucrose", brand: "SweetUms", classification: "Analgesic (Neonatal)" },
  { generic: "tetracaine", brand: "Ametop", classification: "Local Anesthetic" },
  { generic: "thiamine", brand: "Vitamin B1", classification: "Vitamin" },
  { generic: "ticagrelor", brand: "Brilinta", classification: "Antiplatelet" },
  { generic: "tranexamic acid", brand: "Cyklokapron", classification: "Antifibrinolytic" },
  { generic: "trazodone", brand: "Desyrel", classification: "Antidepressant (SARI)" },
  { generic: "vancomycin", brand: "Vancocin", classification: "Antibiotic (Glycopeptide)" },
  { generic: "warfarin", brand: "Coumadin", classification: "Anticoagulant (Vitamin K Antagonist)" }
];

export const CARDIO_DATA = [
  { generic: "Epinephrine", brand: "Adrenalin", classification: "Vasopressor/Adrenergic Agonist" },
  { generic: "Amiodarone", brand: "Cordarone", classification: "Antiarrhythmic (Class III)" },
  { generic: "Lidocaine", brand: "Xylocaine", classification: "Antiarrhythmic (Class Ib)" },
  { generic: "Adenosine", brand: "Adenocard", classification: "Antiarrhythmic (AV Nodal)" },
  { generic: "Atropine", brand: "Atropine", classification: "Anticholinergic" },
  { generic: "Isoproterenol", brand: "Isuprel", classification: "Beta-Adrenergic Agonist" },
  { generic: "Dopamine", brand: "Intropin", classification: "Inotrope/Vasopressor" },
  { generic: "Procainamide", brand: "Pronestyl", classification: "Antiarrhythmic (Class Ia)" },
  { generic: "Calcium chloride", brand: "Calcium Chloride", classification: "Electrolyte" },
  { generic: "Magnesium sulfate", brand: "Magnesium Sulfate", classification: "Electrolyte/Antiarrhythmic" },
  { generic: "Acetylsalicylic acid (ASA)", brand: "Aspirin", classification: "Antiplatelet/NSAID" },
  { generic: "Clopidogrel", brand: "Plavix", classification: "Antiplatelet (P2Y12 Inhibitor)" },
  { generic: "Ticagrelor", brand: "Brilinta", classification: "Antiplatelet (P2Y12 Inhibitor)" },
  { generic: "Prasugrel", brand: "Effient", classification: "Antiplatelet (P2Y12 Inhibitor)" },
  { generic: "Eptifibatide", brand: "Integrilin", classification: "Antiplatelet (GP IIb/IIIa Inhibitor)" },
  { generic: "Tirofiban", brand: "Aggrastat", classification: "Antiplatelet (GP IIb/IIIa Inhibitor)" },
  { generic: "Alteplase", brand: "Activase", classification: "Thrombolytic" },
  { generic: "Tenecteplase", brand: "TNKase", classification: "Thrombolytic" },
  { generic: "Heparin", brand: "Heparin", classification: "Anticoagulant (UFH)" },
  { generic: "Enoxaparin", brand: "Lovenox", classification: "Anticoagulant (LMWH)" },
  { generic: "Dalteparin", brand: "Fragmin", classification: "Anticoagulant (LMWH)" },
  { generic: "Tinzaparin", brand: "Innohep", classification: "Anticoagulant (LMWH)" },
  { generic: "Fondaparinux", brand: "Arixtra", classification: "Anticoagulant (Factor Xa Inhibitor)" },
  { generic: "Warfarin", brand: "Coumadin", classification: "Anticoagulant (Vitamin K Antagonist)" },
  { generic: "Apixaban", brand: "Eliquis", classification: "Anticoagulant (DOAC)" },
  { generic: "Rivaroxaban", brand: "Xarelto", classification: "Anticoagulant (DOAC)" },
  { generic: "Dabigatran", brand: "Pradaxa", classification: "Anticoagulant (Direct Thrombin Inhibitor)" },
  { generic: "Bivalirudin", brand: "Angiomax", classification: "Anticoagulant (Direct Thrombin Inhibitor)" },
  { generic: "Argatroban", brand: "Argatroban", classification: "Anticoagulant (Direct Thrombin Inhibitor)" },
  { generic: "Nitroglycerin", brand: "Nitrostat", classification: "Nitrate/Vasodilator" },
  { generic: "Isosorbide mononitrate", brand: "Imdur", classification: "Nitrate/Vasodilator" },
  { generic: "Isosorbide dinitrate", brand: "Generics", classification: "Nitrate/Vasodilator" },
  { generic: "Metoprolol", brand: "Lopressor", classification: "Beta-Blocker (Cardioselective)" },
  { generic: "Atenolol", brand: "Tenormin", classification: "Beta-Blocker (Cardioselective)" },
  { generic: "Propranolol", brand: "Inderal", classification: "Beta-Blocker (Non-Selective)" },
  { generic: "Bisoprolol", brand: "Monocor", classification: "Beta-Blocker (Cardioselective)" },
  { generic: "Nadolol", brand: "Corgard", classification: "Beta-Blocker (Non-Selective)" },
  { generic: "Acebutolol", brand: "Sectral", classification: "Beta-Blocker (ISA)" },
  { generic: "Timolol", brand: "Blocadren", classification: "Beta-Blocker (Non-Selective)" },
  { generic: "Diltiazem", brand: "Cardizem", classification: "Calcium Channel Blocker (Non-DHP)" },
  { generic: "Verapamil", brand: "Isoptin", classification: "Calcium Channel Blocker (Non-DHP)" },
  { generic: "Calcium gluconate", brand: "Calcium Gluconate", classification: "Electrolyte" },
  { generic: "Potassium chloride", brand: "K-Dur", classification: "Electrolyte" },
  { generic: "Sodium bicarbonate", brand: "Sodium Bicarbonate", classification: "Alkalinizing Agent" },
  { generic: "Insulin (regular)", brand: "Humulin R", classification: "Insulin (Short-Acting)" },
  { generic: "Furosemide", brand: "Lasix", classification: "Loop Diuretic" }
];

export const SUIT_SYMBOLS = {}; // Not used in this app but preserved from template logic if needed
